#!/bin/bash

#  Copyright (C) 2015-2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


if [ "$EUID" -ne 0 ]
  then echo "The script must be run as root."
  exit
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR


if [ -f /bin/systemctl ]; then
	echo -e "\033[0;33mDisabling the systemd daemon...\033[0m"
    systemctl stop akbl
    systemctl disable akbl
fi


echo -e "\033[0;33mRemoving files and directories..\033[0m"

AKBL_PYTHON_VERSIONS=("python3.4" "python3.5" "python3.6" "python3.7" "python3.8" "python3.9")

for python_version in "${AKBL_PYTHON_VERSIONS[@]}"; do

    if [ -f /usr/lib/$python_version/AKBL ] || [ -d /usr/lib/$python_version/AKBL ]; then
        rm -f /usr/lib/$python_version/AKBL && echo -e "\033[0;33m Link AKBL removed from $python_version\033[0m"
    fi 
    if [ -f /usr/lib/$python_version/AKBL.py ] || [ -d /usr/lib/$python_version/AKBL.py ]; then
        rm -f /usr/lib/$python_version/AKBL.py && echo -e "\033[0;33m Link AKBL.py removed from $python_version\033[0m"
    fi 
    
done

if [ -f /usr/bin/akbl ]; then
	rm -f /usr/bin/akbl
fi

if [ -d /usr/share/AKBL ]; then
	rm -rf /usr/share/AKBL
fi

if [ -d /usr/share/doc/AKBL ]; then
	rm -rf /usr/share/doc/AKBL
fi

if [ -d /usr/lib/python3/AKBL ]; then
	rm -rf /usr/lib/python3/AKBL
fi

if [ -f /usr/lib/systemd/system/AKBL.service ]; then
	rm -rf /usr/lib/systemd/system/AKBL.service
fi

if [ -f /usr/share/applications/akbl.desktop ]; then
	rm -f /usr/share/applications/akbl.desktop
fi


if [ "$1" != "-s" ]; then
	echo -e "\e[00;32mAKBL has been removed.\e[00m"
fi
